config/routes.rb
RailsTutorial::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  
  get "raise" => "home#raise", :as => "raise"
  
  

  root :to => 'home#index'

end

app/models/active_model_base.rb
#http://d.hatena.ne.jp/fujisan3776/20110701/1309478262

class ActiveModelBase
  include ActiveModel::Validations
  include ActiveModel::Conversion

  def persisted? ; false ; end

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value) rescue nil
    end
  end
end

app/models/session.rb
# encoding: utf-8
class Session < ActiveModelBase
  
  attr_accessor :identification, :password, :remember_me

  validates :identification, :password, presence: true
  
end

app/models/user.rb
# encoding: utf-8
# == Schema Information
#
# Table name: users
#
#  id                           :integer          not null, primary key
#  name                         :string(255)      not null
#  email                        :string(255)      not null
#  crypted_password             :string(255)
#  salt                         :string(255)
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  remember_me_token            :string(255)
#  remember_me_token_expires_at :datetime
#  avatar_file_name             :string(255)
#  avatar_content_type          :string(255)
#  avatar_file_size             :integer
#  avatar_updated_at            :datetime
#

class EmailAddressValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || I18n.t("activerecord.errors.messages.invalid"))
    end
  end
end

class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessor :remove_avatar
  attr_accessible :name, :email, :password, :password_confirmation, :avatar, :remove_avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  validates :name, :email, presence: true, uniqueness: true
  validates :name, :format => { 
    :with => /\A[a-zA-Z\d_]+\z/, 
    :message => I18n.t("activerecord.errors.messages.invalid") 
  }
  validates :email, email_address: true
  validates :name, length: { in: 4..50 }
  validates :password, length: { in: 8..20 }, :if => :password?
  validates :password, presence: {on: :create}
  validates :password, confirmation: true, :if => :password?
  
  before_save :should_remove_avatar?, :if => :remove_avatar?
  
  class << self
    def name?(guess)
      guess.strip!
      
      if guess =~ /@/
        user = find_by_email guess 
      else
        user = find_by_name guess
      end
      
      return user.name if user
    end
  end
  
  private
    def password?
      password.present?
    end
    
    def remove_avatar?
      not @remove_avatar.to_i.zero?
    end
    
    def should_remove_avatar?
      self.avatar.destroy
      
      true
    end
end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def not_authenticated
    flash[:error] = "ログインしてください"
    redirect_to login_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def raise
    1/0
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController
  def new
    @user_session = Session.new
  end
  
  def create
    @user_session = Session.new params[:session]
    return render :new unless @user_session.valid?
    
#    user_name = User.name?(@user_session.identification)
    
    user = login(@user_session.identification, @user_session.password, @user_session.remember_me)
    if user
      redirect_back_or_to root_url, success: "ログインしました"
    else
      flash.now[:error] = "認証できませんでした"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  before_filter :require_login, :only => :show

  def new
    @user = User.new
    render :form
  end
  
  def create
    @user = User.new params[:user]
    if @user.save
      flash[:success] = "ユーザー登録しました！"
      redirect_to root_url
    else
      render :form
    end
  end
  
  def edit
    find
    render :form
  end
  
  def update
    find
    
    if @user.update_attributes(params[:user].reject{|key| key == :name})
      flash[:success] = "ユーザー編集しました！"
      redirect_to edit_user_path @user
    else
      render :form
    end
  end
  
  private 
    def find
      @user = User.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>welcome</h1>
</div>

<h1><%= link_to "強制エラー（Production時にメールで通知）", raise_path %></h1>

<% if logged_in? %>
  <h1><%= link_to "秘密のリンク", user_path(current_user) %></h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RailsTutorial" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "RailsTutorial", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <% unless logged_in? %>
                <li><%= link_to "ユーザー登録", signup_path  %></li>
                <li><%= link_to "ログイン", login_path  %></li>
              <% end %>
              <% if logged_in? %>
                <li><%= link_to "ユーザー編集", edit_user_path(current_user)  %></li>
                <li><%= link_to "ログアウト", logout_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <% flash.each do |type, message| %>
          <%= content_tag :div, message, class: "alert alert-#{type}" %>
        <% end %>
        <div class="row">
           <%= yield %>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/form.html.erb
<%

  name_options = {}
  name_options = {class: "disabled", disabled: true} unless @user.new_record?
%>

<%= semantic_form_for @user do |form| %>
  <%= form.input :avatar %>
  <% if @user.avatar.file? %>
    <%= image_tag @user.avatar.url :thumb %>
    <%= form.input :remove_avatar, as: :boolean %>
  <% end %>
  <%= form.input :name, input_html: name_options %>
  <%= form.input :email %>
  <%= form.input :password %>
  <%= form.input :password_confirmation %>

  <%= form.actions do %>
    <%= form.action :submit, :as => :button %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<%= semantic_form_for @user do |form| %>
  <%= form.input :name %>
  <%= form.input :email %>
  <%= form.input :password %>
  <%= form.input :password_confirmation %>

  <%= form.actions do %>
    <%= form.action :submit, :as => :button %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="alert alert-block">
  <h4 class="alert-heading">秘密のページ</h4>
  直リンクでもログインしていないと見れないページです。
</div>